schema: kata.ai/schema/merapi/1.0

name: ${package.name}
version: ${package.version}

plugins:
    - express-heroku

components:
    app:
        type: express
        config: app

    api: controllers/ApiController
    scrapperManager: managers/ScrapperManager
    redisRepo: repos/RedisRepo

    main: Main

redis:
    url: ${$REDIS_URL}

app:
    port: ${$PORT}
   
    router:
        mergeParams: true

    routes:
        GET /flightDetails:
            - api.getFlightDetails

# entry point
main: main